### ISSUE TITLE
New Project > Info > Project Path not saving

### ISSUE THREAD

**Issue by JonBrant** [nomnomab/nomnom-unity-hub#5]
It keeps defaulting back to my documents folder. It should save my last used directory

Also could you maybe add me as a collaborator without code access maybe, so I can label?

**Comment by nomnomab** [comment]
It defaults to the path assigned in the settings, the same way as the Unity Hub.

**Comment by JonBrant** [comment]
I uh, yeah I was uh, testing you. You passed! I think. Yeah, that's it
